[cosmic-ray]
module-path = "src"
test-command = "bash -c \"PYTHONPATH=src pytest -q\""
timeout = 10.0

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.operators]
exclude = []

[cosmic-ray.filters]
exclude-modules = ["report"]